# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ProtoMain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ProtoMain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import RocketGroundCommunication_pb2 as RocketGroundCommunication__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fProtoMain.proto\x12\x05Proto\x1a\x1fRocketGroundCommunication.proto\"\xfe\x01\n\x0bMainMessage\x12-\n\x0ein_flight_data\x18\x01 \x01(\x0b\x32\x13.Proto.InFlightDataH\x00\x12=\n\x16switch_radio_frequency\x18\x02 \x01(\x0b\x32\x1b.Proto.SwitchRadioFrequencyH\x00\x12(\n\tdebug_msg\x18\x03 \x01(\x0b\x32\x13.Proto.DebugMessageH\x00\x12,\n\rinfo_exchange\x18\x04 \x01(\x0b\x32\x13.Proto.InfoExchangeH\x00\x12\x19\n\x03\x61\x63k\x18\x05 \x01(\x0b\x32\n.Proto.AckH\x00\x42\x0e\n\x0cmessage_type\"n\n\nLogMessage\x12\x12\n\ntime_stamp\x18\x01 \x01(\r\x12\x10\n\x08severity\x18\x02 \x01(\r\x12\x10\n\x08location\x18\x03 \x01(\r\x12(\n\x0cmain_message\x18\x04 \x01(\x0b\x32\x12.Proto.MainMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ProtoMain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAINMESSAGE']._serialized_start=60
  _globals['_MAINMESSAGE']._serialized_end=314
  _globals['_LOGMESSAGE']._serialized_start=316
  _globals['_LOGMESSAGE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
