# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RocketGroundCommunication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'RocketGroundCommunication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fRocketGroundCommunication.proto\x12\x05Proto\"\x84\x03\n\x0cInFlightData\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\r\x12.\n\x08\x62mp_data\x18\x02 \x01(\x0b\x32\x1c.Proto.InFlightData.BMP_Data\x12\x1e\n\x16\x61\x63\x63\x65l_gyro_temperature\x18\x03 \x01(\x02\x12*\n\x05\x61\x63\x63\x65l\x18\x04 \x01(\x0b\x32\x1b.Proto.InFlightData.VectorF\x12)\n\x04gyro\x18\x05 \x01(\x0b\x32\x1b.Proto.InFlightData.VectorF\x12\x31\n\x0cmagnetometer\x18\x06 \x01(\x0b\x32\x1b.Proto.InFlightData.VectorF\x12\x13\n\x0bthermometer\x18\x07 \x01(\x02\x1a\x43\n\x08\x42MP_Data\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08pressure\x18\x02 \x01(\x02\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x02\x1a*\n\x07VectorF\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\t\n\x01Z\x18\x03 \x01(\x02\"-\n\x14SwitchRadioFrequency\x12\x15\n\rnew_frequency\x18\x01 \x01(\x02\"+\n\x0c\x44\x65\x62ugMessage\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\"B\n\x0cInfoExchange\x12\x15\n\rradio_version\x18\x01 \x01(\r\x12\x1b\n\x13proto_3_msg_version\x18\x02 \x01(\r\"(\n\x03\x41\x63k\x12!\n\x19response_to_which_message\x18\x01 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RocketGroundCommunication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFLIGHTDATA']._serialized_start=43
  _globals['_INFLIGHTDATA']._serialized_end=431
  _globals['_INFLIGHTDATA_BMP_DATA']._serialized_start=320
  _globals['_INFLIGHTDATA_BMP_DATA']._serialized_end=387
  _globals['_INFLIGHTDATA_VECTORF']._serialized_start=389
  _globals['_INFLIGHTDATA_VECTORF']._serialized_end=431
  _globals['_SWITCHRADIOFREQUENCY']._serialized_start=433
  _globals['_SWITCHRADIOFREQUENCY']._serialized_end=478
  _globals['_DEBUGMESSAGE']._serialized_start=480
  _globals['_DEBUGMESSAGE']._serialized_end=523
  _globals['_INFOEXCHANGE']._serialized_start=525
  _globals['_INFOEXCHANGE']._serialized_end=591
  _globals['_ACK']._serialized_start=593
  _globals['_ACK']._serialized_end=633
# @@protoc_insertion_point(module_scope)
